on:
  push:
    branches:
      - 'releases/**'
name: Deploy releases branch on push
jobs:
  web-deploy:
    name: 🎉 Deploy releases
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ftp.test-metall.site
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          local-dir: ./testCiCd/
          server-dir: ./stages/production/
